### ISSUE TITLE
JWSACruncher and parameters `fullseriesname` and `refreshall`

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jdplus-main#112]
I tried the following parameters files an a workspace with data created by an Excel file and it has no effect. Are the parameters `fullseriesname` and `refreshall` suppose to work in the JWSACruncher? Am I doing something wrong?
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<wsaConfig bundle="10000" csvlayout="vtable" csvseparator=";" ndecs="6" fullseriesname="false" rsltnamelevel="2" format="JD3">
    <policy>parameters</policy>
    <refreshall>true</refreshall>
    <matrix>
        <item>period</item>
        <item>log</item>
    </matrix>
    <tsmatrix>
        <series>y</series>
        <series>sa</series>
    </tsmatrix>
</wsaConfig>
```
And
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<wsaConfig bundle="10000" csvlayout="vtable" csvseparator=";" ndecs="6" fullseriesname="true" rsltnamelevel="2" format="JD3">
    <policy>parameters</policy>
    <refreshall>false</refreshall>
    <matrix>
        <item>period</item>
        <item>log</item>
    </matrix>
    <tsmatrix>
        <series>y</series>
        <series>sa</series>
    </tsmatrix>
</wsaConfig>
```

**Comment by ChristianeHofer** [comment]
Refreshall was fixed in 3.1.0 with f9a83377e3c3c0ef3f7793485504c471daf28ee6.

**Comment by AQLT** [comment]
@charphi @ChristianeHofer: so the fullseriesname parameter was also fixed in 3.1.0?

**Comment by charphi** [comment]
The `fullseriesname` parameter is not currently used, and I don't know what @palatej had in mind 😄

**Comment by AQLT** [comment]
Then could you please reopen the issue since it is not completely solved? The `fullseriesname` parameter must be associated to the "full series name" option in the interface ("if false only the name of the series will be displayed")

**Comment by charphi** [comment]
Screenshot for reference:

![Screenshot 2024-06-11 145010](https://github.com/jdemetra/jdplus-main/assets/8778378/309709ee-c4d8-4ded-a633-9bb2d043ae0e)
